name = "ACSets"
uuid = "227ef7b5-1206-438b-ac65-934d6da304b8"
license = "MIT"
authors = ["Owen Lynch <owen@topos.institute>", "Kris Brown <kris@topos.institute>", "Evan Patterson <evan@epatters.org>", "AlgebraicJulia Team"]
version = "0.2.6"

[deps]
CompTime = "0fb5dd42-039a-4ca4-a1d7-89a96eae6d39"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
MLStyle = "d8e11817-5142-5d16-987a-aa16d5891078"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Permutations = "2ae35dd2-176d-5d53-8349-f30d82d94d4f"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StructEquality = "6ec83bb0-ed9f-11e9-3b4c-2b04cb4e219c"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[weakdeps]
XLSX = "fdbf4ff8-1666-58a4-91e7-1b58723a45e0"
nauty_jll = "55c6dc9b-343a-50ca-8ff2-b71adb3733d5"

[extensions]
NautyACSetsExt = "nauty_jll"
XLSXACSetsExt = "XLSX"

[compat]
CompTime = "0.1"
DataStructures = "0.18"
JSON = "0.21"
MLStyle = "0.4"
OrderedCollections = "1"
Permutations = "0.4"
PrettyTables = "2.2"
Reexport = "1"
StaticArrays = "1"
StructEquality = "2.1"
Tables = "1"
XLSX = "0.10"
julia = "1.9"
