name = "ACSets"
uuid = "227ef7b5-1206-438b-ac65-934d6da304b8"
license = "MIT"
authors = ["Owen Lynch <owen@topos.institute>", "Kris Brown <kris@topos.institute>", "Evan Patterson <evan@epatters.org>", "AlgebraicJulia Team"]
version = "0.0.1"

[deps]
CompTime = "0fb5dd42-039a-4ca4-a1d7-89a96eae6d39"
MLStyle = "d8e11817-5142-5d16-987a-aa16d5891078"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StructEquality = "6ec83bb0-ed9f-11e9-3b4c-2b04cb4e219c"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
CompTime = "0.1"
MLStyle = "0.4"
PrettyTables = "2.2"
Reexport = "1"
StaticArrays = "1"
StructEquality = "2.1"
Tables = "1"
julia = "1.9"
