name = "AlgebraicTemplate"
uuid = "b66562e1-fa90-4e8b-9505-c909188fab76"
license = "MIT"
authors = ["AlgebraicJulia Developer <email@algebraicjulia.org>"]
version = "0.0.1"

[deps]
Catlab = "134e5e36-593f-5add-ad60-77f754baafbe"

[compat]
Catlab = "^0.14"
julia = "1.6"
